WindowManager:
    Welcome:

<Welcome>:
    name: "Welcome"
    FloatLayout:
        size: root.width, root.height
        canvas:
            Color:
                rgb: 107/255, 232/255, 247/255
            Rectangle:
                pos: self.pos
                size: self.size

        # Language Toggle Button
        Button:
            text: 'ES' if app.translator.get_current_language() == 'en' else 'EN'
            font_size: 20
            size_hint: (0.1, 0.1)
            pos_hint: {'right': 0.98, 'top': 0.98}
            background_color: (1, 0.8, 0, 1)
            on_release: app.toggle_language()

        Label:
            text: app.welcome_text
            font_size: 40
            color: 0, 0, 0
            pos_hint: {'center_x': 0.5, 'center_y': 0.8}

        Label:
            text: app.username_text
            font_size: 30
            color: 0, 0, 0
            pos_hint: {'center_x': 0.3, 'center_y': 0.6}

        Label:
            text: app.password_text
            font_size: 30
            color: 0, 0, 0
            pos_hint: {'center_x': 0.3, 'center_y': 0.5}

        Button:
            text: app.login_text
            font_size: 25
            size_hint: (0.2, 0.1)
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            background_color: (0, 0.8, 0, 1)
